use std::cmp::Ordering;
use std::collections::BTreeMap;

use crate::domain::ids::RoleId;
use crate::domain::profile::{Certification, Contact, Education, Profile, Role, Skill};
use crate::error::{CoreError, CoreResult};

/// A single word (or short run) of text extracted from a PDF page.
///
/// Coordinates are in PDF points: `x` grows to the right from the page's left
/// edge, `y` grows *downward* from the page's top edge. `width` is the run's
/// advance. Extraction is I/O and lives in the CLI; this type is the pure
/// boundary between the two.
#[derive(Debug, Clone, PartialEq)]
pub struct PositionedRun {
    pub page: usize,
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub size: f64,
    pub text: String,
}

/// Positioned text from a whole PDF, in content-stream order.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct PositionedLayout {
    pub runs: Vec<PositionedRun>,
}

impl PositionedLayout {
    /// Flatten to reading-order text.
    ///
    /// Column-aware, so it is far more legible than the raw content-stream
    /// order. Used as the input to the optional LLM structuring fallback.
    pub fn to_text(&self) -> String {
        let mut out = String::new();
        for line in build_lines(self) {
            out.push_str(line.text.trim());
            out.push('\n');
        }
        out
    }
}

/// Parse a LinkedIn "Save to PDF" resume from positioned text.
///
/// The LinkedIn export is generated by Apache FOP as a two-column document
/// with localized section headings. This parser splits the columns by
/// x-position and reads each column top-to-bottom with a heading-keyed state
/// machine, so it stays deterministic and offline. It is tuned to that single
/// template; anything else is expected to fail validation and be retried by the
/// optional LLM fallback.
pub fn parse_linkedin_pdf(layout: &PositionedLayout) -> CoreResult<Profile> {
    let lines = build_lines(layout);
    if lines.is_empty() {
        return Err(CoreError::parse("PDF contained no extractable text"));
    }

    let body_size = dominant_size(&lines);
    let header_min = body_size * 1.15;
    let heading_min = body_size * 1.05;

    let mut columns: Vec<usize> = lines.iter().map(|line| line.column).collect();
    columns.sort_unstable();
    columns.dedup();

    let main_column = *columns
        .iter()
        .max_by(|a, b| {
            max_size_in_column(&lines, **a)
                .partial_cmp(&max_size_in_column(&lines, **b))
                .unwrap_or(Ordering::Equal)
        })
        .expect("at least one column");

    let mut profile = Profile::default();
    for column in columns {
        let column_lines: Vec<&Line> = lines.iter().filter(|line| line.column == column).collect();
        let (preamble, blocks) = split_sections(&column_lines, header_min);
        for (section, block) in blocks {
            apply_section(&mut profile, section, &block, body_size, heading_min);
        }
        if column == main_column {
            interpret_preamble(&mut profile, &preamble);
        }
    }

    if profile.name.trim().is_empty() {
        return Err(CoreError::parse(
            "could not find a name; this does not look like a LinkedIn resume PDF",
        ));
    }
    Ok(profile)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Section {
    Contact,
    TopSkills,
    Languages,
    Certifications,
    Summary,
    Experience,
    Education,
    Projects,
}

struct Line {
    page: usize,
    column: usize,
    y: f64,
    size: f64,
    text: String,
}

/// Split runs into per-column lines, ordered left column first, top-to-bottom.
fn build_lines(layout: &PositionedLayout) -> Vec<Line> {
    let runs: Vec<&PositionedRun> = layout
        .runs
        .iter()
        .filter(|run| !run.text.trim().is_empty() && !is_page_marker(run.text.trim()))
        .collect();
    if runs.is_empty() {
        return Vec::new();
    }

    let boundary = column_boundary(&runs);
    let mut groups: BTreeMap<(usize, usize, i64), Vec<&PositionedRun>> = BTreeMap::new();
    for run in runs {
        let column = if run.x < boundary { 0 } else { 1 };
        let key = (run.page, column, (run.y / 3.0).round() as i64);
        groups.entry(key).or_default().push(run);
    }

    let mut lines = Vec::with_capacity(groups.len());
    for ((page, column, _), mut group) in groups {
        group.sort_by(|a, b| a.x.partial_cmp(&b.x).unwrap_or(Ordering::Equal));
        let size = group.iter().map(|run| run.size).fold(0.0, f64::max);
        let y = group.iter().map(|run| run.y).sum::<f64>() / group.len() as f64;
        let text = group
            .iter()
            .map(|run| normalize_spaces(run.text.trim()))
            .collect::<Vec<_>>()
            .join(" ");
        if is_page_marker(&text) {
            continue;
        }
        lines.push(Line {
            page,
            column,
            y,
            size,
            text,
        });
    }

    lines.sort_by(|a, b| {
        a.page
            .cmp(&b.page)
            .then(a.column.cmp(&b.column))
            .then(a.y.partial_cmp(&b.y).unwrap_or(Ordering::Equal))
    });
    lines
}

/// Find the x-position that separates the two columns, or infinity if the
/// document is single-column.
///
/// Runs are merged into occupied x-intervals; the widest empty band between
/// them is the gutter. Widths matter: a right-aligned word in the left column
/// leaves an empty x-*start* gap that is not actually empty.
fn column_boundary(runs: &[&PositionedRun]) -> f64 {
    let mut intervals: Vec<(f64, f64)> = runs
        .iter()
        .map(|run| (run.x, run.x + run.width.max(1.0)))
        .collect();
    intervals.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(Ordering::Equal));

    let mut merged: Vec<(f64, f64)> = Vec::new();
    for (start, end) in intervals {
        match merged.last_mut() {
            Some(last) if start <= last.1 => last.1 = last.1.max(end),
            _ => merged.push((start, end)),
        }
    }
    if merged.len() < 2 {
        return f64::INFINITY;
    }

    let (boundary, gap) = merged
        .windows(2)
        .map(|pair| ((pair[0].1 + pair[1].0) / 2.0, pair[1].0 - pair[0].1))
        .max_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(Ordering::Equal))
        .expect("at least two intervals");
    if gap >= 25.0 {
        boundary
    } else {
        f64::INFINITY
    }
}

fn split_sections<'a>(
    lines: &[&'a Line],
    header_min: f64,
) -> (Vec<&'a Line>, Vec<(Section, Vec<&'a Line>)>) {
    let mut preamble = Vec::new();
    let mut blocks: Vec<(Section, Vec<&Line>)> = Vec::new();
    let mut current: Option<Section> = None;

    for line in lines {
        let header = if line.size >= header_min {
            section_for(&line.text)
        } else {
            None
        };
        if let Some(section) = header {
            current = Some(section);
            blocks.push((section, Vec::new()));
            continue;
        }
        match current {
            None => preamble.push(*line),
            Some(_) => blocks
                .last_mut()
                .expect("a block exists once a section is active")
                .1
                .push(line),
        }
    }
    (preamble, blocks)
}

fn apply_section(
    profile: &mut Profile,
    section: Section,
    block: &[&Line],
    body_size: f64,
    heading_min: f64,
) {
    match section {
        Section::Contact => {
            for line in block {
                parse_contact_line(&line.text, &mut profile.contact);
            }
        }
        Section::TopSkills => {
            for line in block {
                let name = line.text.trim();
                if !name.is_empty() {
                    profile.skills.push(Skill {
                        name: name.to_string(),
                        level: None,
                    });
                }
            }
        }
        Section::Languages => {}
        Section::Certifications => {
            for entry in group_entries(block, body_size) {
                profile.certifications.push(Certification {
                    name: entry,
                    issuer: None,
                    year: None,
                });
            }
        }
        Section::Summary => {
            let text = join_paragraph(block);
            if !text.is_empty() {
                profile.summary = Some(text);
            }
        }
        Section::Experience => parse_experience(profile, block, heading_min),
        Section::Education => parse_education(profile, block, heading_min),
        Section::Projects => {}
    }
}

fn parse_contact_line(text: &str, contact: &mut Contact) {
    let text = text.trim();
    let lower = text.to_lowercase();
    if text.contains('@') && contact.email.is_none() {
        contact.email = Some(text.to_string());
    } else if lower.contains("linkedin.com") && contact.linkedin.is_none() {
        contact.linkedin = Some(text.to_string());
    } else if lower.contains("github.com") && contact.github.is_none() {
        contact.github = Some(text.to_string());
    } else if is_phone(text) && contact.phone.is_none() {
        contact.phone = Some(text.to_string());
    } else if (lower.starts_with("http") || lower.starts_with("www.")) && contact.website.is_none()
    {
        contact.website = Some(text.to_string());
    }
}

/// Group wrapped lines into entries by leading: a larger-than-normal vertical
/// gap starts a new entry.
fn group_entries(lines: &[&Line], body_size: f64) -> Vec<String> {
    let threshold = body_size * 1.4;
    let mut entries = Vec::new();
    let mut current = String::new();
    let mut previous_y: Option<f64> = None;

    for line in lines {
        let text = line.text.trim();
        if text.is_empty() {
            continue;
        }
        let starts_new = previous_y.map(|y| line.y - y > threshold).unwrap_or(true);
        if starts_new && !current.is_empty() {
            entries.push(std::mem::take(&mut current));
        }
        push_wrapped(&mut current, text);
        previous_y = Some(line.y);
    }
    if !current.is_empty() {
        entries.push(current);
    }
    entries
}

fn parse_experience(profile: &mut Profile, block: &[&Line], heading_min: f64) {
    let mut company = String::new();
    let mut current: Option<Role> = None;
    let mut description = String::new();
    let mut expect_location = false;

    for (index, line) in block.iter().enumerate() {
        let text = line.text.trim();
        if text.is_empty() {
            continue;
        }

        if line.size >= heading_min {
            let next_is_date = block
                .get(index + 1)
                .map(|next| is_date_range(next.text.trim()))
                .unwrap_or(false);
            if next_is_date {
                flush_role(profile, &mut current, &mut description);
                current = Some(Role {
                    id: RoleId::generate(profile.roles.len() + 1),
                    title: text.to_string(),
                    organization: company.clone(),
                    location: None,
                    start: None,
                    end: None,
                    current: false,
                    bullets: Vec::new(),
                    skills: Vec::new(),
                });
                expect_location = true;
            } else {
                flush_role(profile, &mut current, &mut description);
                company = text.to_string();
            }
            continue;
        }

        let Some(role) = current.as_mut() else {
            continue;
        };

        if is_date_range(text) {
            let (start, end) = split_dates(text);
            role.current = end
                .as_deref()
                .map(|end| {
                    let end = fold(end);
                    end.contains("present") || end.contains("atual")
                })
                .unwrap_or(false);
            role.start = Some(start);
            role.end = end;
            expect_location = true;
            continue;
        }
        if is_tenure(text) {
            continue;
        }
        if expect_location && role.location.is_none() && is_location(text) {
            role.location = Some(text.to_string());
            expect_location = false;
            continue;
        }
        expect_location = false;
        push_wrapped(&mut description, text);
    }

    flush_role(profile, &mut current, &mut description);
}

fn flush_role(profile: &mut Profile, role: &mut Option<Role>, description: &mut String) {
    let text = description.trim().to_string();
    if let Some(mut role) = role.take() {
        if !text.is_empty() {
            role.bullets.push(text);
        }
        profile.roles.push(role);
    }
    description.clear();
}

fn parse_education(profile: &mut Profile, block: &[&Line], heading_min: f64) {
    let mut current: Option<Education> = None;
    let mut detail = String::new();

    for line in block {
        let text = line.text.trim();
        if text.is_empty() {
            continue;
        }
        if line.size >= heading_min {
            flush_education(profile, &mut current, &mut detail);
            current = Some(Education {
                degree: None,
                institution: text.to_string(),
                field: None,
                start: None,
                end: None,
            });
        } else if current.is_some() {
            if !detail.is_empty() {
                detail.push(' ');
            }
            detail.push_str(text);
        }
    }

    flush_education(profile, &mut current, &mut detail);
}

fn flush_education(profile: &mut Profile, education: &mut Option<Education>, detail: &mut String) {
    if let Some(mut education) = education.take() {
        let detail = detail.trim().to_string();
        let (body, dates) = match detail.split_once('·').or_else(|| detail.split_once('•')) {
            Some((body, dates)) => (body.trim().to_string(), Some(dates.trim().to_string())),
            None => (detail, None),
        };
        if let Some(dates) = dates {
            let (start, end) = split_dates(&dates);
            education.start = Some(start);
            education.end = end;
        }
        if !body.is_empty() {
            match body.split_once(',') {
                Some((degree, field)) => {
                    education.degree = Some(degree.trim().to_string());
                    let field = field.trim();
                    if !field.is_empty() {
                        education.field = Some(field.to_string());
                    }
                }
                None => education.degree = Some(body),
            }
        }
        profile.education.push(education);
    }
    detail.clear();
}

fn interpret_preamble(profile: &mut Profile, preamble: &[&Line]) {
    let Some((name_index, name_line)) = preamble
        .iter()
        .enumerate()
        .max_by(|(_, a), (_, b)| a.size.partial_cmp(&b.size).unwrap_or(Ordering::Equal))
    else {
        return;
    };
    profile.name = name_line.text.trim().to_string();

    let mut headline = Vec::new();
    let mut location = None;
    for (index, line) in preamble.iter().enumerate() {
        if index == name_index {
            continue;
        }
        let text = line.text.trim();
        if text.is_empty() {
            continue;
        }
        if text.contains('|') {
            headline.push(text.to_string());
        } else if location.is_none() && text.contains(',') && text.len() < 60 {
            location = Some(text.to_string());
        } else {
            headline.push(text.to_string());
        }
    }
    if !headline.is_empty() {
        let mut joined = String::new();
        for part in &headline {
            push_wrapped(&mut joined, part);
        }
        profile.headline = Some(joined);
    }
    if location.is_some() {
        profile.location = location;
    }
}

fn join_paragraph(lines: &[&Line]) -> String {
    let mut out = String::new();
    for line in lines {
        push_wrapped(&mut out, line.text.trim());
    }
    out
}

/// Append wrapped text, joining at a hyphen without inserting a space.
fn push_wrapped(buffer: &mut String, text: &str) {
    let text = text.trim();
    if text.is_empty() {
        return;
    }
    if !buffer.is_empty() && !buffer.ends_with('-') {
        buffer.push(' ');
    }
    buffer.push_str(text);
}

fn dominant_size(lines: &[Line]) -> f64 {
    let mut counts: BTreeMap<i64, usize> = BTreeMap::new();
    for line in lines {
        *counts.entry((line.size * 2.0).round() as i64).or_default() += 1;
    }
    counts
        .into_iter()
        .max_by(|a, b| a.1.cmp(&b.1).then(b.0.cmp(&a.0)))
        .map(|(size, _)| size as f64 / 2.0)
        .unwrap_or(11.0)
}

fn max_size_in_column(lines: &[Line], column: usize) -> f64 {
    lines
        .iter()
        .filter(|line| line.column == column)
        .map(|line| line.size)
        .fold(0.0, f64::max)
}

fn section_for(text: &str) -> Option<Section> {
    let key = fold(text.trim().trim_end_matches(':'));
    match key.as_str() {
        "contact" | "contato" => Some(Section::Contact),
        "top skills" | "principais competencias" | "competencias" | "skills" | "habilidades" => {
            Some(Section::TopSkills)
        }
        "languages" | "idiomas" | "linguas" => Some(Section::Languages),
        "certifications" | "certificacoes" | "certificados" => Some(Section::Certifications),
        "summary" | "resumo" | "about" | "sobre" => Some(Section::Summary),
        "experience" | "experiencia" => Some(Section::Experience),
        "education" | "formacao academica" | "formacao" | "educacao" => Some(Section::Education),
        "projects" | "projetos" => Some(Section::Projects),
        _ => None,
    }
}

fn is_page_marker(text: &str) -> bool {
    let folded = fold(text);
    (folded.starts_with("page ") && folded.contains(" of "))
        || (folded.starts_with("pagina ") && folded.contains(" de "))
}

fn is_date_range(text: &str) -> bool {
    text.len() < 80
        && has_year(text)
        && (text.contains(" - ") || text.contains('–') || text.contains(" -"))
}

fn is_tenure(text: &str) -> bool {
    if has_year(text) {
        return false;
    }
    let folded = fold(text);
    text.len() < 40
        && (folded.contains("ano")
            || folded.contains("mes")
            || folded.contains("year")
            || folded.contains("month"))
}

fn is_location(text: &str) -> bool {
    if has_year(text) || text.len() >= 60 || text.contains('|') {
        return false;
    }
    let folded = fold(text);
    folded == "remoto" || folded == "remote" || text.contains(',')
}

fn is_phone(text: &str) -> bool {
    let digits = text.chars().filter(|c| c.is_ascii_digit()).count();
    digits >= 7 && text.chars().any(|c| c == '+' || c == '(' || c == '-')
}

fn has_year(text: &str) -> bool {
    let mut run = 0;
    for ch in text.chars() {
        if ch.is_ascii_digit() {
            run += 1;
            if run >= 4 {
                return true;
            }
        } else {
            run = 0;
        }
    }
    false
}

fn split_dates(text: &str) -> (String, Option<String>) {
    let mut text = text.trim();
    if text.starts_with('(') && text.ends_with(')') {
        text = &text[1..text.len() - 1];
    }
    if text.ends_with(')') {
        if let Some(index) = text.rfind(" (") {
            text = &text[..index];
        }
    }
    let text = text.trim();
    let parts = text.split_once(" - ").or_else(|| text.split_once('–'));
    match parts {
        Some((start, end)) => (start.trim().to_string(), Some(end.trim().to_string())),
        None => (text.to_string(), None),
    }
}

/// Collapse every Unicode space (including non-breaking spaces, which the
/// LinkedIn export uses around date separators) to a plain space.
fn normalize_spaces(text: &str) -> String {
    text.chars()
        .map(|c| if c.is_whitespace() { ' ' } else { c })
        .collect()
}

/// Lowercase and strip accents so localized headings match one dictionary.
fn fold(text: &str) -> String {
    text.chars()
        .map(|c| match c {
            'á' | 'à' | 'â' | 'ã' | 'ä' | 'å' | 'Á' | 'À' | 'Â' | 'Ã' | 'Ä' | 'Å' => {
                'a'
            }
            'é' | 'è' | 'ê' | 'ë' | 'É' | 'È' | 'Ê' | 'Ë' => 'e',
            'í' | 'ì' | 'î' | 'ï' | 'Í' | 'Ì' | 'Î' | 'Ï' => 'i',
            'ó' | 'ò' | 'ô' | 'õ' | 'ö' | 'Ó' | 'Ò' | 'Ô' | 'Õ' | 'Ö' => 'o',
            'ú' | 'ù' | 'û' | 'ü' | 'Ú' | 'Ù' | 'Û' | 'Ü' => 'u',
            'ç' | 'Ç' => 'c',
            'ñ' | 'Ñ' => 'n',
            other => other,
        })
        .flat_map(char::to_lowercase)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn run(page: usize, x: f64, y: f64, size: f64, text: &str) -> PositionedRun {
        PositionedRun {
            page,
            x,
            y,
            width: text.chars().count() as f64 * size * 0.35,
            size,
            text: text.to_string(),
        }
    }

    fn left(y: f64, size: f64, text: &str) -> PositionedRun {
        run(0, 21.6, y, size, text)
    }

    fn right(y: f64, size: f64, text: &str) -> PositionedRun {
        run(0, 223.6, y, size, text)
    }

    const HEADER: f64 = 18.3;
    const RIGHT_HEADER: f64 = 22.2;
    const COMPANY: f64 = 16.9;
    const TITLE: f64 = 16.2;
    const BODY: f64 = 14.8;
    const NAME: f64 = 36.6;

    fn sample_layout() -> PositionedLayout {
        let runs = vec![
            // Left column.
            left(40.0, HEADER, "Contato"),
            left(63.0, BODY, "jane.doe@example.com"),
            left(86.0, BODY, "www.linkedin.com/in/janedoe"),
            left(114.0, BODY, "github.com/janedoe (Portfolio)"),
            left(147.0, HEADER, "Principais competências"),
            left(169.0, BODY, "Programação de sistemas"),
            left(187.0, BODY, "Desenvolvimento de software"),
            left(236.0, HEADER, "Languages"),
            left(258.0, BODY, "Espanhol (Full Professional)"),
            left(379.0, HEADER, "Certifications"),
            left(401.0, BODY, "Open-Source Intelligence (OSINT)"),
            left(416.0, BODY, "Fundamentals"),
            left(441.0, BODY, "Introdução à Filosofia: dos pré-"),
            left(456.0, BODY, "socráticos a Sartre"),
            left(481.0, BODY, "Fundamentals of Database"),
            left(496.0, BODY, "Engineering"),
            left(521.0, BODY, "Learn Linux Kernel Programming"),
            // Right column preamble.
            right(38.0, NAME, "Jane Doe"),
            right(74.0, BODY, "Backend Engineer || Golang | Rust |"),
            right(88.0, BODY, "Linux Power User ||"),
            right(104.0, BODY, "São Carlos, São Paulo, Brasil"),
            // Summary.
            right(137.0, RIGHT_HEADER, "Resumo"),
            right(
                167.0,
                BODY,
                "Backend developer with four years of experience.",
            ),
            right(185.0, BODY, "Interested in programming language design."),
            // Experience.
            right(342.0, RIGHT_HEADER, "Experiência"),
            right(377.0, COMPANY, "Acme Corp"),
            right(395.0, BODY, "2 anos 6 meses"),
            right(415.0, TITLE, "Senior Software Engineer II"),
            right(431.0, BODY, "junho de 2024 - Present (2 anos 4 meses)"),
            right(446.0, BODY, "São Carlos, São Paulo, Brasil"),
            right(
                467.0,
                BODY,
                "Led the migration of a critical service to Kafka.",
            ),
            right(587.0, TITLE, "Software Engineer I"),
            right(603.0, BODY, "abril de 2024 - junho de 2024 (3 meses)"),
            right(618.0, BODY, "São Carlos, São Paulo, Brasil"),
            right(
                639.0,
                BODY,
                "Built a SQL-like interface over ElasticSearch.",
            ),
            // Education.
            run(1, 223.6, 475.0, RIGHT_HEADER, "Formação acadêmica"),
            run(1, 223.6, 505.0, COMPANY, "University of London"),
            run(
                1,
                223.6,
                524.0,
                BODY,
                "Bacharelado em Ciências da Computação, Ciência da Computação · (março",
            ),
            run(1, 223.6, 542.0, BODY, "de 2018 - outubro de 2022)"),
            run(1, 384.0, 768.0, 12.7, "Page 1 of 2"),
        ];
        PositionedLayout { runs }
    }

    #[test]
    fn parses_a_linkedin_resume() {
        let profile = parse_linkedin_pdf(&sample_layout()).unwrap();
        assert_eq!(profile.name, "Jane Doe");
        assert_eq!(
            profile.headline.as_deref(),
            Some("Backend Engineer || Golang | Rust | Linux Power User ||")
        );
        assert_eq!(
            profile.location.as_deref(),
            Some("São Carlos, São Paulo, Brasil")
        );
        assert_eq!(
            profile.contact.email.as_deref(),
            Some("jane.doe@example.com")
        );
        assert_eq!(
            profile.contact.linkedin.as_deref(),
            Some("www.linkedin.com/in/janedoe")
        );
        assert_eq!(
            profile.contact.github.as_deref(),
            Some("github.com/janedoe (Portfolio)")
        );
        assert_eq!(profile.skills.len(), 2);
        assert!(profile.summary.as_deref().unwrap().contains("four years"));
        assert_eq!(profile.certifications.len(), 4);
        assert_eq!(
            profile.certifications[0].name,
            "Open-Source Intelligence (OSINT) Fundamentals"
        );
        assert_eq!(
            profile.certifications[1].name,
            "Introdução à Filosofia: dos pré-socráticos a Sartre"
        );
        assert_eq!(profile.roles.len(), 2);
        assert_eq!(profile.roles[0].organization, "Acme Corp");
        assert_eq!(profile.roles[0].title, "Senior Software Engineer II");
        assert_eq!(profile.roles[0].start.as_deref(), Some("junho de 2024"));
        assert_eq!(profile.roles[0].end.as_deref(), Some("Present"));
        assert!(profile.roles[0].current);
        assert_eq!(
            profile.roles[0].location.as_deref(),
            Some("São Carlos, São Paulo, Brasil")
        );
        assert_eq!(profile.roles[0].bullets.len(), 1);
        assert_eq!(profile.roles[1].organization, "Acme Corp");
        assert_eq!(profile.roles[1].title, "Software Engineer I");
        assert_eq!(profile.education.len(), 1);
        assert_eq!(profile.education[0].institution, "University of London");
        assert_eq!(
            profile.education[0].degree.as_deref(),
            Some("Bacharelado em Ciências da Computação")
        );
        assert_eq!(
            profile.education[0].field.as_deref(),
            Some("Ciência da Computação")
        );
        assert_eq!(profile.education[0].start.as_deref(), Some("março de 2018"));
        assert_eq!(profile.education[0].end.as_deref(), Some("outubro de 2022"));
    }

    #[test]
    fn requires_a_name() {
        let layout = PositionedLayout {
            runs: vec![
                left(40.0, HEADER, "Contato"),
                left(63.0, BODY, "jane@example.com"),
            ],
        };
        assert!(parse_linkedin_pdf(&layout).is_err());
    }

    #[test]
    fn rejects_empty_layout() {
        assert!(parse_linkedin_pdf(&PositionedLayout::default()).is_err());
    }

    #[test]
    fn drops_languages_and_page_markers() {
        let profile = parse_linkedin_pdf(&sample_layout()).unwrap();
        assert!(profile
            .skills
            .iter()
            .all(|skill| !skill.name.contains("Espanhol")));
    }

    #[test]
    fn flattens_to_reading_order_text() {
        let text = sample_layout().to_text();
        let name = text.find("Jane Doe").unwrap();
        let summary = text.find("Resumo").unwrap();
        assert!(name < summary);
        assert!(!text.contains("Page 1 of 2"));
    }
}
